service: SLS-TEMPLATE

plugins:
  - serverless-offline
  - serverless-webpack

frameworkVersion: "3"

useDotenv: true

provider:
  # GENERAL
  name: aws
  runtime: ${env:AWS_RUNTIME}
  stage: ${opt:stage}
  region: ${env:AWS_REGION}
  timeout: ${env:SLS_TIMEOUT} # Por defecto es 30 segundos, establecer a 300 seg para un correcto debug
  # IAM
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:*"
          Resource: "*"

custom:
  webpack:
    includeModules: true
  serverless-offline:
    useChildProcesses: true
    useWorkerThreads: false

package:
  excludeDevDependencies: false
  include:
    - node_modules/** # Incluye el directorio de módulos
    - dist/** # Incluye el directorio de distribución
    - .env # Incluye el archivo de variables de entorno

functions:
  - ${file(src/modules/samples/serverless/events.yaml)}